<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Create Stream Log' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Update {modelClass}: ' => 'Aktualisiere {modelClass}',
    'menu.login' => 'Login',
    'menu.stream' => 'Stream',
    'Active' => 'Aktiv',
    'Code' => 'Code',
    'Config' => 'Konfiguration',
    'Create' => 'Erstellen',
    'Create Stream' => 'Erstelle Stream',
    'Create User' => 'Erstelle Benutzer',
    'Created At' => 'Erstellt am',
    'Delete' => 'Löschen',
    'Description' => 'Beschreibung',
    'Details' => 'Details',
    'Email' => 'E-Mail',
    'End' => 'Endet',
    'ID' => 'Kennung',
    'Modified At' => 'Verändert am',
    'Modified By' => 'Verändert von',
    'Name' => 'Name',
    'Parent' => 'Eltern',
    'Start' => 'Beginn',
    'Status' => 'Status',
    'Stream ID' => 'Stream Kennung',
    'Stream Logs' => 'Stream Logs',
    'Streams' => 'Streams',
    'Timestamp' => 'Zeitstempel',
    'Type' => 'Typ',
    'Update' => 'Aktualisieren',
    'Updated At' => 'Aktualisiert am',
    'Url' => 'URL',
    'Username' => 'Benutzer',
    'Users' => 'Benutzer',
    'Value' => 'Wert',
    'Description before form' => 'Beschreibung vor Input',
    'Frame URL' => 'URL für iFrame Anbindung'
];
