<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'button.send' => 'Abschicken',
    'info.footer.about' => 'Digital Deacon gibt dir die Möglichkeit deine Termine auch im Netz zu zeigen.',
    'menu.links' => 'Links',
    'menu.stream.details' => 'Details über den Stream',
    'error.code.invalid' => 'Ihr eingegebener Code ist inkorrekt!',
    'info.start.usage' => 'Um den Stream zu schauen benötigen sei einen Berechtigungscode, den sie hier eingeben müssen. Wenn sie keinen gültigen Code besitzen wenden sie sich an: shop@ebtc-media.org.',
];
